### ISSUE TITLE
Region growing

### ISSUE THREAD

**Issue by jaimebayes** [jlengrand/image_processing#1]
Hi Julien,

I am trying to understand why the order of the seed elements are using inverted (y,x), to obtain the mean_reg value, and to assign the gray values to region, like this reg[cur_pix[1], cur_pix[0]], but for the current_pixel you use the normal order (x,y).

The only solution that I found to make the result match with original image, is to invert the x,y values of the seed parameter previously, I mean, when I am calling the function simple_region_growing, this way:

> > > seed = ([y,x])
> > > simple_region_growing(img, seed, threshold)

Is it the way you intend? or I am doing wrong?

Thanks in advance, Jaime

**Comment by nithingopi** [comment]
Do you have the python implementation of fuzzy connectedness based image segmentation. if then could you add it your repository.


thank you

**Comment by jlengrand** [comment]
@nithingopi Sorry, I don't. But if you do, feel free to create a PR and I'd be happy to add to it. Also, next time please create a separate issue :).

**Comment by jlengrand** [comment]
That makes me realize that I still haven't answered you @jaimebayes :s, sorry for that. Is the question still open for you? 
I have to admit that I wrote this code over 6 years ago so I'd have to get back into it if you need help

**Comment by nithingopi** [comment]
Thank you julien. i am working on the implementation. once i complete i wil
defenitely create a PR.

cheers
nithin

**Comment by nithingopi** [comment]
The issue i am still facing is the seed point selection using mouse click.
Using matlab it can be done using the ginput() function . do you have any
idea how it can be done in python.

Thanks
nithin

**Comment by jlengrand** [comment]
@nithingopi You can find how this is done in the code here : https://github.com/jlengrand/image_processing/blob/master/region_growing/basic_operations.py#L16

Hope this helps :)

**Comment by nithingopi** [comment]
yeah it worked.... thank you so much julien.
